### ISSUE TITLE
Pollyfil not working

### ISSUE THREAD

**Issue by paulolieuthier** [fxos-components/gaia-components#2]
You've got really great components there, I'd really like to use them. However, I can't get them to work with Polymer's or X-Tag's pollyfils. Is it possible? Does it need any special hack?

**Comment by gasolin** [comment]
After a quick check I think gaia components are not ready for cross browser use now...
1. web component is not default enabled in browsers yet, and depends on gecko api (object.fetch)
2. es6 arrow functions is not supported in chrome & IE
3. CSS variable is firefox only at this time

for 1. webcomponent.js & some gecko API polyfill will help. for 2 & 3 the transpiler may help gaia-components work for other browsers.

**Comment by paulolieuthier** [comment]
@gasolin I was actually trying that on my Mozilla Flame device.

**Comment by paulolieuthier** [comment]
I could get it working after enabling `dom.webcomponents.enabled`.

**Comment by gasolin** [comment]
Ooh, if you mean fxos, you don't need any polyfiill on fxos 2.1+ device.

**Comment by paulolieuthier** [comment]
I'll try again someday. Thanks.
